# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 534dbc6db4c6793dd2cfe1d3b4ba4d8cd92e133e228b73cf5adb472b6d4a3996c323b58e0b12bb106ed2c9e82ea67a9bfe7c1109a322e5f7c5f8473ba3f3a084

test:
  secret_key_base: c8e3255fe6f4d64b11aff7006454d3ad86840d0455e4d59caccecfcd941886c5a0996205363beeacdffb55b0a7b7c8db0e5ecaccd3a5ba722c717418aa74f7f5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
